# docker continuous delivery
# deliver docker images to configured repo with tags to match branches and git tags
---
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git commit
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set environment variable for version from git output
        run: echo "REACT_APP_VERSION_STRING=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Publish to GitHub Container Registry
        # TODO: pin to hash
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          registry: ghcr.io

          # GitHub actor
          username: ${{ github.actor }}

          # GitHub access token
          password: ${{ secrets.GITHUB_TOKEN }}

          # create docker image tags to match git tags
          tag_names: true
          buildargs: VERSION_STRING

      # # TODO remove after every *-environments migrated to GHCR
      - name: Publish to Dockerhub registry
        # todo: pin to hash
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
          name: ${{ secrets.DOCKER_REPO }}
          # configured at repo settings/secrets
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # create docker image tags to match git tags
          tag_names: true
          buildargs: REACT_APP_VERSION_STRING
